[build-system]
requires = ["setuptools", "meson-python", "pybind11[global]"]
build-backend = "mesonpy"

[project]
name = "sbio"
description="Stream Broker IO - Data Processing Framework for Streamed Data."
requires-python = ">=3.8"
dynamic = ["version"]
dependencies = [
    "ncarray>=0.7.3",
]
authors = [
    { name = "Gabriel Dorlhiac", email = "gabriel@dorlhiac.com" },
]
readme = "README.md"
urls = { Changelog = "https://github.com/XFELPP/sbio/blob/main/CHANGELOG.md" }
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: GPU",
    "Environment :: GPU :: NVIDIA CUDA",
    "Environment :: GPU :: NVIDIA CUDA :: 12",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: GNU Affero General Public License v3",
    "Operating System :: POSIX :: Linux",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: MacOS",
    "Natural Language :: English",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: C++",
    "Topic :: Scientific/Engineering",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

[tool.meson-python.args]
install = ['--skip-subprojects']

# Refer to utilities for CIBW configuration TOMLs
