[tool.cibuildwheel]
# pp* (PyPy for now)
# cp36-* (Python 3.6)
# cp37-* (Python 3.7)
# *i686 (32-bit builds)
skip = ["pp*", "cp36-*", "cp37-*", "*i686", "*-win32"]

# Maybe redundant, but specify what we do build
build = ["cp38-*", "cp39-*", "cp310-*", "cp311-*", "cp312-*", "cp313-*"]

# Try to set things up to cache what's possible to make things faster
build-frontend = { name = "pip", args = ["--no-build-isolation"] }

before-build = [
    "python -m pip install -U pip",
    "python -m pip install \"meson>=1.10.1\" meson-python ninja \"pybind11[global]\" setuptools cmake delvewheel",
    "python -m pip install ncarray==0.7.1 --extra-index-url https://pypi.xfelpp.org/host"
]

# For C++23 need a newer GCC coming from manylinux_2_28 (GCC 13) and later
# manylinux_2_34 will give GCC 14
manylinux-x86_64-image = "manylinux_2_28"
manylinux-aarch64-image = "manylinux_2_28"

config-settings = { "setup-args" = ["-Dbuild_core=false"] }

[tool.cibuildwheel.linux]
# The CI YAML pulls cuda-toolkit and determines version.
# Just setup links here.
before-all = [
    """
    if command -v apt-get >/dev/null; then
        apt-get update && apt-get install -y ccache
        apt-get update && apt-get install -y libopenmpi-dev
    elif command -v dnf >/dev/null; then
        dnf install -y epel-release && dnf install -y ccache
        dnf install -y openmpi openmpi-devel
    elif command -v yum >/dev/null; then
        yum install -y epel-release && yum install -y ccache
        yum install -y openmpi openmpi-devel
    elif command -v apk >/dev/null; then
        apk add ccache
    fi
    ccache -z

    mkdir install
    /opt/python/cp310-cp310/bin/pip install meson ninja
    /opt/python/cp310-cp310/bin/python -m pip install ncarray==0.7.1 --extra-index-url https://pypi.xfelpp.org/host || true
    export PATH="/usr/lib64/openmpi/bin:/opt/python/cp310-cp310/bin:$PATH"
    meson setup builddir -Dbuild_core=true -Dbuild_python=true -Dsbio_as_wheel=true -Dbuild_mpi=auto --prefix={project}/install
    meson compile -j 2 -C builddir
    meson install -C builddir
    """,
]
repair-wheel-command = "python utilities/repair_wheel.py {wheel} {dest_dir} --no-exclude-core"

[tool.cibuildwheel.linux.environment]
CC = "ccache gcc"
CXX = "ccache g++"
CCACHE_DIR = "/project/.ccache"
PIP_RETRIES = "20"
LIBRARY_PATH = "/project/install/lib:/project/install/lib64:$LIBRARY_PATH"
LD_LIBRARY_PATH = "/project/install/lib:/project/install/lib64:$LD_LIBRARY_PATH"
LDFLAGS = "-L/project/install/lib -L/project/install/lib64"

[tool.cibuildwheel.macos]
before-all = """
brew install open-mpi ccache ninja meson cmake || true
ccache -z
python3 -m pip install ncarray==0.7.1 --extra-index-url https://pypi.xfelpp.org/host || true
meson setup builddir -Dbuild_core=true -Dbuild_python=true -Dsbio_as_wheel=true -Dbuild_mpi=auto --prefix=$(pwd)/install
meson compile -j 2 -C builddir
meson install -C builddir
"""

[tool.cibuildwheel.macos.environment]
CC = "ccache clang"
CXX = "ccache clang++"
CCACHE_DIR = ".ccache"
PIP_RETRIES = "20"
MACOSX_DEPLOYMENT_TARGET = "11.0"
# Not able to find cmake in wheel step otherwise?
PATH = "/opt/homebrew/bin:/usr/local/bin:/Applications/CMake.app/Contents/bin:$PATH"
LIBRARY_PATH = "$GITHUB_WORKSPACE/install/lib:$LIBRARY_PATH"
DYLD_LIBRARY_PATH = "$GITHUB_WORKSPACE/install/lib:$DYLD_LIBRARY_PATH"
LDFLAGS = "-L$GITHUB_WORKSPACE/install/lib"

[tool.cibuildwheel.windows]
config-settings = { "setup-args" = ["-Dcpp_compiler_launcher=", "-Dcuda_compiler_launcher=", "-Dbuild_core=false"] }
before-all = [
    "choco install msmpi -y",
    "python -m pip install meson ninja",
    "python -m pip install ncarray==0.7.1 --extra-index-url https://pypi.xfelpp.org/host",
    "meson setup builddir -Dbuild_core=true -Dbuild_python=true -Dsbio_as_wheel=true -Dbuild_mpi=auto --prefix=%CD%/install",
    "meson compile -j 2 -C builddir",
    "meson install -C builddir"
]
repair-wheel-command = "python utilities/repair_wheel_win.py {dest_dir} {wheel} --no-exclude-core"

[tool.cibuildwheel.windows.environment]
PIP_RETRIES = "20"
LIB = "$GITHUB_WORKSPACE/install/lib;$LIB"
PATH = "$GITHUB_WORKSPACE/install/bin;$PATH"
PreferredToolArchitecture = "x64"
